# Generated by Django 4.0.5 on 2022-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0002_alter_member_passingyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='age',
            field=models.IntegerField(),
        ),
    ]
