# Generated by Django 4.0.5 on 2022-08-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0005_file_remove_problem_id_submission_submission_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='code_data',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
