# Generated by Django 4.0.5 on 2022-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0007_code_remove_file_code_data_alter_file_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
        migrations.AddField(
            model_name='file',
            name='code_data',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
