# Generated by Django 4.0.5 on 2022-09-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0008_delete_code_file_code_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='verdict',
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_output',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
