# Generated by Django 4.0.5 on 2022-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0009_delete_file_remove_submission_submission_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='file',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='correct_output',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='input_file',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='input_case',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='output_case',
        ),
        migrations.AddField(
            model_name='test_cases',
            name='correct_output',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='test_cases',
            name='input_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
