# Generated by Django 4.0.5 on 2022-09-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website_OJ', '0010_rename_file_submission_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_cases',
            name='id',
        ),
        migrations.AddField(
            model_name='test_cases',
            name='p_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
